#!/bin/bash
docker tag docker-cloud:agent-uid-2k varshavs/docker-cloud:agent-uid-2k
docker tag docker-cloud:agent-uid-3k varshavs/docker-cloud:agent-uid-3k
docker push varshavs/docker-cloud:agent-uid-2k
docker push varshavs/docker-cloud:agent-uid-3k
